// This code is generated by ChatGPT and is intended for latency testing purposes only. 
// It creates a JSON file with 200 pet records
// IMPORTANT: I have gotten confirmation of using ChatGPT for creating the massive dataset by my supervisor.


const fs = require("fs");

const TOTAL_RECORDS = 400;

const speciesData = {
  dog: ["shiba inu", "german shepherd", "corgi", "husky", "beagle"],
  cat: ["british shorthair", "siamese", "maine coon", "ragdoll"],
  rabbit: ["lop", "rex", "netherland dwarf"],
  bird: ["parakeet", "cockatiel", "canary"],
  hamster: ["syrian", "dwarf"],
  turtle: ["red-eared slider"],
  snake: ["corn snake", "ball python"],
  lizard: ["gecko", "bearded dragon"],
  ferret: ["unknown"],
  guinea_pig: ["american", "abyssinian"],
  hedgehog: ["african pygmy"]
};

const names = ["Mochi","Yuki","Hana","Kuma","Nori","Miso","Sora","Kuro","Luna","N/A"];
const genders = ["male","female","unknown"];
const shelters = ["shelterA","shelterB","shelterC","shelterD"];

const adoptionStatuses = ["AVAILABLE","RESERVED","ADOPTED"];

const ownerNames = [
  "John Doe","Jane Doe","Max Müller","Anna Schmidt",
  "Lukas Weber","Emily Brown","Ken Tanaka","Maria Garcia"
];

const cities = ["Leipzig","Berlin","Munich","Düsseldorf","Kyoto","Tokyo","Hamburg"];


function random(arr){
  return arr[Math.floor(Math.random()*arr.length)];
}

function randomChip(){
  return Math.random() < 0.3
    ? ""
    : String(Math.floor(1e14 + Math.random()*9e14));
}

function randomPhone(){
  return Math.random() < 0.3
    ? null
    : String(Math.floor(10000000000 + Math.random()*89999999999));
}

function randomCity(){
  return Math.random() < 0.3
    ? null
    : random(cities);
}

function createOwner(){
  return {
    name: random(ownerNames),
    phone: randomPhone(),
    city: randomCity()
  };
}

function generateFormerOwners(){

  const owners = [];
  const count = Math.floor(Math.random()*4); // 0-3 former owners

  for(let i=0;i<count;i++){
    owners.push(createOwner());
  }

  return owners;
}

const animals = [];

for (let i = 1; i <= TOTAL_RECORDS; i++) {

  const species = random(Object.keys(speciesData));

  const animal = {
    animalId: `${species}${String(i).padStart(3,"0")}`,
    name: random(names),
    species: species,
    breed: random(speciesData[species]),
    gender: random(genders),
    age: Math.random() < 0.2 ? "unknown" : String(Math.floor(Math.random()*15)),
    shelterId: random(shelters),
    microchipNumber: randomChip(),
    vaccination: Math.random() < 0.5 ? "true":"false",
    notes: Math.random() < 0.4 ? "" : "Test sample data",
    adoptionStatus: random(adoptionStatuses)
  };

  const ownerMode = Math.random();

  // 30% → no owner fields
  if(ownerMode < 0.3){

  }

  // 30% → current owner only
  else if(ownerMode < 0.6){

    animal.currentOwner = createOwner();
    animal.formerOwners = [];

  }

  // 40% → former owners only OR mix
  else{

    const former = generateFormerOwners();

    if(Math.random() < 0.5){
      animal.currentOwner = createOwner();
    }

    animal.formerOwners = former;

  }

  animals.push(animal);
}

fs.writeFileSync("pets400.json", JSON.stringify(animals,null,2));

console.log(`Generated ${animals.length} records`);